// Arquivo inicial do layout da aplicação Next.js. Aqui na raiz ele é necessario para definir o layout global da aplicação, como a estrutura HTML básica e os metadados. Ja nas demais rotas é opcional, mas é muito utilizado para definir o layout de uma rota específica, uma estrutura padronizada para todas as páginas daquela rota, como cabeçalho, rodapé, etc.

// Em todo layout contem um children que representa o conteúdo da página que será renderizado dentro do layout. O Next.js irá substituir esse children pelo conteúdo da página atual quando renderizar a aplicação. E todas as rotas usam o layout de seu pai até chegar na raiz, onde o layout é o global da aplicação.

import type { Metadata } from 'next'
import './globals.css'
import { Menu } from '@/components/menu'

// Objeto para definir metatags da head de forma simples nas paginas. Você pode definir o título, descrição, palavras-chave, autor, etc. Se quiser pode fazer isso em um layout acima, ou seja, de alguma rota especifica, ou até mesmo em uma page/pagina especifica. Se não definir isso em cada pagina, eles vão utilizar o que foi definido no layout global, ou seja, na raiz da aplicação.
export const metadata: Metadata = {
  title: 'Origamid Next',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <Menu />
        {children}
      </body>
    </html>
  )
}
