// Arquivo inicial do layout da aplicação Next.js

import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Origamid Next.js',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body>{children}</body>
    </html>
  )
}
