GET http://localhost:3000/api

###
POST http://localhost:3000/api?busca=dog

{
  "user": {
    "id": 1,
    "name": "John Doe"
  }
}

### Conta
GET http://localhost:3000/api/conta

### Perfil
GET http://localhost:3000/api/perfil


